%% Import data from text file
% Script for importing data from the following text file:
%
%    filename: C:\Users\knewcomb1\MichaelGroup\2Variant\covid_coronavirusapp_statelevel\b117cases.csv
%
% Auto-generated by MATLAB on 12-Jul-2021 15:07:33

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 5, "Encoding", "UTF-8");

% Specify range and delimiter
opts.DataLines = [1, Inf];
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["date", "alpha", "delta", "omi", "ba2", "ba4", "ba5"];
opts.VariableTypes = ["datetime", "double", "double", "double", "double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, "date", "InputFormat", "MM/dd/yyyy");

% Import the data
cases = readtable("./b117cases_new.csv", opts);

dates = table2array(cases(:, 1));
frac1  = table2array(cases(:, 2))./100;
frac2  = table2array(cases(:, 3))./100;
frac3  = table2array(cases(:, 4))./100;
frac4  = table2array(cases(:, 5))./100;
frac5  = table2array(cases(:, 6))./100;
frac6  = table2array(cases(:, 7))./100;


[x, y, z] = intersect(timeRef, dates);
dates = y;
firstdate = y(1);
lastindex = y(end)+1;
dates = [(1:firstdate)'; dates;(lastindex:1000)';];
lastval = frac1(end);
lastval2 = frac2(end);
lastval3 = frac3(end);
lastval4 = frac4(end)+frac5(end)+frac6(end);
lastval5 = frac5(end);
lastval6 = frac6(end);


frac1 = [0.*(1:firstdate)'; frac1; lastval+0*(lastindex:1000)'];
frac2 = [0.*(1:firstdate)'; frac2; lastval2+0*(lastindex:1000)'];
frac3 = [0.*(1:firstdate)'; frac3; lastval3+0*(lastindex:1000)'];
frac4 = [0.*(1:firstdate)'; frac4+frac5+frac6; lastval4+0*(lastindex:1000)'];
%frac5 = [0.*(1:firstdate)'; frac5; lastval5+0*(lastindex:1000)'];
%frac6 = [0.*(1:firstdate)'; frac6; lastval6+0*(lastindex:1000)'];

%% Clear temporary variables
clear opts